// <auto-generated />
using System;
using Backend.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(SupplyChainDbContext))]
    [Migration("20260102075027_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.Data.Entities.alert", b =>
                {
                    b.Property<Guid>("alert_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("cleared_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("material_id")
                        .HasColumnType("uuid");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("node_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("raised_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("alert_id")
                        .HasName("alerts_pkey");

                    b.HasIndex("material_id");

                    b.HasIndex("node_id");

                    b.HasIndex("severity");

                    b.HasIndex(new[] { "category", "node_id", "material_id", "raised_at" }, "uq_alert_instance")
                        .IsUnique();

                    b.ToTable("alerts", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.alert_category", b =>
                {
                    b.Property<string>("category")
                        .HasColumnType("text");

                    b.HasKey("category");

                    b.ToTable("alert_categories", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.alert_severity", b =>
                {
                    b.Property<string>("severity")
                        .HasColumnType("text");

                    b.HasKey("severity");

                    b.ToTable("alert_severities", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.audit_event", b =>
                {
                    b.Property<Guid>("audit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("details")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("entity_id")
                        .HasColumnType("uuid");

                    b.Property<string>("entity_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("audit_id");

                    b.ToTable("audit_events", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.daily_plan", b =>
                {
                    b.Property<Guid>("plan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("plan_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("published_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("plan_id")
                        .HasName("daily_plans_pkey");

                    b.HasIndex(new[] { "plan_date", "version" }, "uq_plan_version")
                        .IsUnique();

                    b.ToTable("daily_plans", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.empty_car_release", b =>
                {
                    b.Property<Guid>("release_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("portal_txn_id")
                        .HasColumnType("text");

                    b.Property<string>("railcar_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("released_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("source_ref")
                        .HasColumnType("text");

                    b.HasKey("release_id")
                        .HasName("empty_car_releases_pkey");

                    b.HasIndex("railcar_id");

                    b.ToTable("empty_car_releases", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.inventory_snapshot", b =>
                {
                    b.Property<Guid>("snapshot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("as_of")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("material_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("node_id")
                        .HasColumnType("uuid");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("snapshot_id")
                        .HasName("inventory_snapshots_pkey");

                    b.HasIndex("material_id");

                    b.HasIndex(new[] { "node_id", "material_id", "as_of" }, "uq_inventory")
                        .IsUnique();

                    b.ToTable("inventory_snapshots", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.material", b =>
                {
                    b.Property<Guid>("material_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("hazardous")
                        .HasColumnType("boolean");

                    b.HasKey("material_id")
                        .HasName("materials_pkey");

                    b.HasIndex(new[] { "code" }, "materials_code_key")
                        .IsUnique();

                    b.ToTable("materials", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.material_design_limit", b =>
                {
                    b.Property<Guid>("material_id")
                        .HasColumnType("uuid");

                    b.Property<int>("safety_stock")
                        .HasColumnType("integer");

                    b.Property<int>("target_units")
                        .HasColumnType("integer");

                    b.HasKey("material_id");

                    b.ToTable("material_design_limits", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.mv_current_inventory", b =>
                {
                    b.Property<DateTime?>("as_of")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("material_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("node_id")
                        .HasColumnType("uuid");

                    b.Property<int?>("quantity")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("mv_current_inventory", (string)null);
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.mv_daily_receipt", b =>
                {
                    b.Property<long?>("arrivals")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("node_id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("receipt_date")
                        .HasColumnType("date");

                    b.ToTable("mv_daily_receipts", "public");

                    b.ToView("mv_daily_receipts", (string)null);
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.mv_release_vs_unload", b =>
                {
                    b.Property<DateOnly?>("business_date")
                        .HasColumnType("date");

                    b.Property<long?>("delta")
                        .HasColumnType("bigint");

                    b.Property<long?>("released_cnt")
                        .HasColumnType("bigint");

                    b.Property<long?>("unloaded_cnt")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("mv_release_vs_unload", (string)null);
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.node", b =>
                {
                    b.Property<Guid>("node_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("design_capacity")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("node_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tz")
                        .HasColumnType("text");

                    b.HasKey("node_id")
                        .HasName("nodes_pkey");

                    b.HasIndex("node_type");

                    b.HasIndex(new[] { "name" }, "nodes_name_key")
                        .IsUnique();

                    b.ToTable("nodes", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.node_type", b =>
                {
                    b.Property<string>("node_type1")
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("node_type1");

                    b.ToTable("node_types", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.operation", b =>
                {
                    b.Property<Guid>("operation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("max_daily_unloads")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("plant_node_id")
                        .HasColumnType("uuid");

                    b.HasKey("operation_id")
                        .HasName("operations_pkey");

                    b.HasIndex("plant_node_id");

                    b.ToTable("operations", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.plan_unload", b =>
                {
                    b.Property<Guid>("plan_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("node_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("material_id")
                        .HasColumnType("uuid");

                    b.Property<int>("target_units")
                        .HasColumnType("integer");

                    b.HasKey("plan_id", "node_id", "material_id")
                        .HasName("plan_unloads_pkey");

                    b.HasIndex("material_id");

                    b.HasIndex("node_id");

                    b.ToTable("plan_unloads", (string)null);
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.railcar", b =>
                {
                    b.Property<string>("railcar_id")
                        .HasColumnType("text");

                    b.Property<string>("check_digit")
                        .HasColumnType("text");

                    b.HasKey("railcar_id")
                        .HasName("railcars_pkey");

                    b.ToTable("railcars", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.railcar_movement", b =>
                {
                    b.Property<Guid>("movement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("event_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("from_node")
                        .HasColumnType("uuid");

                    b.Property<Guid>("material_id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("railcar_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("source_ref")
                        .HasColumnType("text");

                    b.Property<Guid>("to_node")
                        .HasColumnType("uuid");

                    b.HasKey("movement_id");

                    b.HasIndex("from_node");

                    b.HasIndex("material_id");

                    b.HasIndex("to_node");

                    b.HasIndex(new[] { "railcar_id", "to_node", "event_time" }, "uq_movement")
                        .IsUnique();

                    b.ToTable("railcar_movements", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.silo", b =>
                {
                    b.Property<Guid>("silo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("max_units")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("plant_node_id")
                        .HasColumnType("uuid");

                    b.HasKey("silo_id");

                    b.HasIndex(new[] { "plant_node_id", "name" }, "silos_plant_node_id_name_key")
                        .IsUnique();

                    b.ToTable("silos", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.silo_material_capacity", b =>
                {
                    b.Property<Guid>("silo_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("material_id")
                        .HasColumnType("uuid");

                    b.Property<int>("max_units")
                        .HasColumnType("integer");

                    b.HasKey("silo_id", "material_id");

                    b.HasIndex("material_id");

                    b.ToTable("silo_material_capacity");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_attachment", b =>
                {
                    b.Property<Guid>("attachment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content_type")
                        .HasColumnType("text");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("mail_id")
                        .HasColumnType("uuid");

                    b.Property<string>("stored_path")
                        .HasColumnType("text");

                    b.HasKey("attachment_id");

                    b.HasIndex("mail_id");

                    b.ToTable("staging_attachments", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_email", b =>
                {
                    b.Property<Guid>("mail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("received_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sender")
                        .HasColumnType("text");

                    b.Property<string>("source_label")
                        .HasColumnType("text");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("mail_id");

                    b.ToTable("staging_emails", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_row", b =>
                {
                    b.Property<Guid>("row_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("attachment_id")
                        .HasColumnType("uuid");

                    b.Property<string>("key")
                        .HasColumnType("text");

                    b.Property<DateTime>("parsed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("row_id");

                    b.HasIndex("attachment_id");

                    b.ToTable("staging_rows", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.supplier", b =>
                {
                    b.Property<Guid>("supplier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("supplier_id");

                    b.HasIndex(new[] { "name" }, "suppliers_name_key")
                        .IsUnique();

                    b.ToTable("suppliers", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.system_parameter", b =>
                {
                    b.Property<string>("param_key")
                        .HasColumnType("text");

                    b.Property<string>("param_value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("param_key");

                    b.ToTable("system_parameters", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.unloading_event", b =>
                {
                    b.Property<Guid>("unload_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("material_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("operation_id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("railcar_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("source_ref")
                        .HasColumnType("text");

                    b.Property<DateTime>("unloaded_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("unload_id");

                    b.HasIndex("material_id");

                    b.HasIndex("operation_id");

                    b.HasIndex("railcar_id");

                    b.ToTable("unloading_events", "public");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.v_plan_compliance", b =>
                {
                    b.Property<long?>("actual_unloads")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("compliance_pct")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("plan_date")
                        .HasColumnType("date");

                    b.Property<Guid?>("plan_id")
                        .HasColumnType("uuid");

                    b.Property<long?>("planned_units")
                        .HasColumnType("bigint");

                    b.Property<int?>("version")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("v_plan_compliance", (string)null);
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.alert", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.alert_category", "categoryNavigation")
                        .WithMany("alerts")
                        .HasForeignKey("category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithMany("alerts")
                        .HasForeignKey("material_id");

                    b.HasOne("Backend.Data.Data.Entities.node", "node")
                        .WithMany("alerts")
                        .HasForeignKey("node_id");

                    b.HasOne("Backend.Data.Data.Entities.alert_severity", "severityNavigation")
                        .WithMany("alerts")
                        .HasForeignKey("severity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryNavigation");

                    b.Navigation("material");

                    b.Navigation("node");

                    b.Navigation("severityNavigation");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.empty_car_release", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.railcar", "railcar")
                        .WithMany("empty_car_releases")
                        .HasForeignKey("railcar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("railcar");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.inventory_snapshot", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithMany("inventory_snapshots")
                        .HasForeignKey("material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.node", "node")
                        .WithMany("inventory_snapshots")
                        .HasForeignKey("node_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");

                    b.Navigation("node");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.material_design_limit", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithOne("material_design_limit")
                        .HasForeignKey("Backend.Data.Data.Entities.material_design_limit", "material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.node", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.node_type", "node_typeNavigation")
                        .WithMany("nodes")
                        .HasForeignKey("node_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("node_typeNavigation");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.operation", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.node", "plant_node")
                        .WithMany("operations")
                        .HasForeignKey("plant_node_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plant_node");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.plan_unload", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithMany("plan_unloads")
                        .HasForeignKey("material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.node", "node")
                        .WithMany("plan_unloads")
                        .HasForeignKey("node_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.daily_plan", "plan")
                        .WithMany("plan_unloads")
                        .HasForeignKey("plan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");

                    b.Navigation("node");

                    b.Navigation("plan");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.railcar_movement", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.node", "from_nodeNavigation")
                        .WithMany("railcar_movementfrom_nodeNavigations")
                        .HasForeignKey("from_node");

                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithMany("railcar_movements")
                        .HasForeignKey("material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.railcar", "railcar")
                        .WithMany("railcar_movements")
                        .HasForeignKey("railcar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.node", "to_nodeNavigation")
                        .WithMany("railcar_movementto_nodeNavigations")
                        .HasForeignKey("to_node")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("from_nodeNavigation");

                    b.Navigation("material");

                    b.Navigation("railcar");

                    b.Navigation("to_nodeNavigation");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.silo", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.node", "plant_node")
                        .WithMany("silos")
                        .HasForeignKey("plant_node_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plant_node");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.silo_material_capacity", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithMany("silo_material_capacities")
                        .HasForeignKey("material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.silo", "silo")
                        .WithMany("silo_material_capacities")
                        .HasForeignKey("silo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");

                    b.Navigation("silo");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_attachment", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.staging_email", "mail")
                        .WithMany("staging_attachments")
                        .HasForeignKey("mail_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mail");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_row", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.staging_attachment", "attachment")
                        .WithMany("staging_rows")
                        .HasForeignKey("attachment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attachment");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.unloading_event", b =>
                {
                    b.HasOne("Backend.Data.Data.Entities.material", "material")
                        .WithMany("unloading_events")
                        .HasForeignKey("material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.operation", "operation")
                        .WithMany("unloading_events")
                        .HasForeignKey("operation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Data.Entities.railcar", "railcar")
                        .WithMany("unloading_events")
                        .HasForeignKey("railcar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");

                    b.Navigation("operation");

                    b.Navigation("railcar");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.alert_category", b =>
                {
                    b.Navigation("alerts");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.alert_severity", b =>
                {
                    b.Navigation("alerts");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.daily_plan", b =>
                {
                    b.Navigation("plan_unloads");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.material", b =>
                {
                    b.Navigation("alerts");

                    b.Navigation("inventory_snapshots");

                    b.Navigation("material_design_limit");

                    b.Navigation("plan_unloads");

                    b.Navigation("railcar_movements");

                    b.Navigation("silo_material_capacities");

                    b.Navigation("unloading_events");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.node", b =>
                {
                    b.Navigation("alerts");

                    b.Navigation("inventory_snapshots");

                    b.Navigation("operations");

                    b.Navigation("plan_unloads");

                    b.Navigation("railcar_movementfrom_nodeNavigations");

                    b.Navigation("railcar_movementto_nodeNavigations");

                    b.Navigation("silos");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.node_type", b =>
                {
                    b.Navigation("nodes");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.operation", b =>
                {
                    b.Navigation("unloading_events");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.railcar", b =>
                {
                    b.Navigation("empty_car_releases");

                    b.Navigation("railcar_movements");

                    b.Navigation("unloading_events");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.silo", b =>
                {
                    b.Navigation("silo_material_capacities");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_attachment", b =>
                {
                    b.Navigation("staging_rows");
                });

            modelBuilder.Entity("Backend.Data.Data.Entities.staging_email", b =>
                {
                    b.Navigation("staging_attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
